from .random_sampling import RandomSampling
from .random_sampling_otf import RandomSamplingOTF
from .bald_reg import BALD_reg
from.only_ssl import Only_SSL
from .uncertain_al_confident_ssl import Uncertain_AL_Confident_SSL
from .uncertain_al_confident_ssl_allremaining import Uncertain_AL_Confident_SSL_AllRemaining